begin_unit
begin_include
include|#
directive|include
file|"cache.h"
end_include
begin_include
include|#
directive|include
file|"diff.h"
end_include
begin_include
include|#
directive|include
file|"diffcore.h"
end_include
begin_comment
comment|/*  * Idea here is very simple.  *  * We have total of (sz-N+1) N-byte overlapping sequences in buf whose  * size is sz.  If the same N-byte sequence appears in both source and  * destination, we say the byte that starts that sequence is shared  * between them (i.e. copied from source to destination).  *  * For each possible N-byte sequence, if the source buffer has more  * instances of it than the destination buffer, that means the  * difference are the number of bytes not copied from source to  * destination.  If the counts are the same, everything was copied  * from source to destination.  If the destination has more,  * everything was copied, and destination added more.  *  * We are doing an approximation so we do not really have to waste  * memory by actually storing the sequence.  We just hash them into  * somewhere around 2^16 hashbuckets and count the occurrences.  *  * The length of the sequence is arbitrarily set to 8 for now.  */
end_comment
begin_define
DECL|macro|HASHBASE
define|#
directive|define
name|HASHBASE
value|65537
end_define
begin_comment
DECL|macro|HASHBASE
comment|/* next_prime(2^16) */
end_comment
begin_function
DECL|function|hash_chars
specifier|static
name|void
name|hash_chars
parameter_list|(
name|unsigned
name|char
modifier|*
name|buf
parameter_list|,
name|unsigned
name|long
name|sz
parameter_list|,
name|int
modifier|*
name|count
parameter_list|)
block|{
name|unsigned
name|int
name|accum1
decl_stmt|,
name|accum2
decl_stmt|,
name|i
decl_stmt|;
comment|/* an 8-byte shift register made of accum1 and accum2.  New 	 * bytes come at LSB of accum2, and shifted up to accum1 	 */
for|for
control|(
name|i
operator|=
name|accum1
operator|=
name|accum2
operator|=
literal|0
init|;
name|i
operator|<
literal|7
condition|;
name|i
operator|++
operator|,
name|sz
operator|--
control|)
block|{
name|accum1
operator|=
operator|(
name|accum1
operator|<<
literal|8
operator|)
operator||
operator|(
name|accum2
operator|>>
literal|24
operator|)
expr_stmt|;
name|accum2
operator|=
operator|(
name|accum2
operator|<<
literal|8
operator|)
operator||
operator|*
name|buf
operator|++
expr_stmt|;
block|}
while|while
condition|(
name|sz
condition|)
block|{
name|accum1
operator|=
operator|(
name|accum1
operator|<<
literal|8
operator|)
operator||
operator|(
name|accum2
operator|>>
literal|24
operator|)
expr_stmt|;
name|accum2
operator|=
operator|(
name|accum2
operator|<<
literal|8
operator|)
operator||
operator|*
name|buf
operator|++
expr_stmt|;
comment|/* We want something that hashes permuted byte 		 * sequences nicely; simpler hash like (accum1 ^ 		 * accum2) does not perform as well. 		 */
name|i
operator|=
operator|(
name|accum1
operator|+
name|accum2
operator|*
literal|0x61
operator|)
operator|%
name|HASHBASE
expr_stmt|;
name|count
index|[
name|i
index|]
operator|++
expr_stmt|;
name|sz
operator|--
expr_stmt|;
block|}
block|}
end_function
begin_function
DECL|function|diffcore_count_changes
name|int
name|diffcore_count_changes
parameter_list|(
name|void
modifier|*
name|src
parameter_list|,
name|unsigned
name|long
name|src_size
parameter_list|,
name|void
modifier|*
name|dst
parameter_list|,
name|unsigned
name|long
name|dst_size
parameter_list|,
name|unsigned
name|long
name|delta_limit
parameter_list|,
name|unsigned
name|long
modifier|*
name|src_copied
parameter_list|,
name|unsigned
name|long
modifier|*
name|literal_added
parameter_list|)
block|{
name|int
modifier|*
name|src_count
decl_stmt|,
modifier|*
name|dst_count
decl_stmt|,
name|i
decl_stmt|;
name|unsigned
name|long
name|sc
decl_stmt|,
name|la
decl_stmt|;
if|if
condition|(
name|src_size
operator|<
literal|8
operator|||
name|dst_size
operator|<
literal|8
condition|)
return|return
operator|-
literal|1
return|;
name|src_count
operator|=
name|xcalloc
argument_list|(
name|HASHBASE
operator|*
literal|2
argument_list|,
sizeof|sizeof
argument_list|(
name|int
argument_list|)
argument_list|)
expr_stmt|;
name|dst_count
operator|=
name|src_count
operator|+
name|HASHBASE
expr_stmt|;
name|hash_chars
argument_list|(
name|src
argument_list|,
name|src_size
argument_list|,
name|src_count
argument_list|)
expr_stmt|;
name|hash_chars
argument_list|(
name|dst
argument_list|,
name|dst_size
argument_list|,
name|dst_count
argument_list|)
expr_stmt|;
name|sc
operator|=
name|la
operator|=
literal|0
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|HASHBASE
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
name|src_count
index|[
name|i
index|]
operator|<
name|dst_count
index|[
name|i
index|]
condition|)
block|{
name|la
operator|+=
name|dst_count
index|[
name|i
index|]
operator|-
name|src_count
index|[
name|i
index|]
expr_stmt|;
name|sc
operator|+=
name|src_count
index|[
name|i
index|]
expr_stmt|;
block|}
else|else
comment|/* i.e. if (dst_count[i]<= src_count[i]) */
name|sc
operator|+=
name|dst_count
index|[
name|i
index|]
expr_stmt|;
block|}
operator|*
name|src_copied
operator|=
name|sc
expr_stmt|;
operator|*
name|literal_added
operator|=
name|la
expr_stmt|;
name|free
argument_list|(
name|src_count
argument_list|)
expr_stmt|;
return|return
literal|0
return|;
block|}
end_function
end_unit
