begin_unit
begin_ifndef
ifndef|#
directive|ifndef
name|COMPAT_TERMINAL_H
end_ifndef
begin_define
DECL|macro|COMPAT_TERMINAL_H
define|#
directive|define
name|COMPAT_TERMINAL_H
end_define
begin_function_decl
name|char
modifier|*
name|git_terminal_prompt
parameter_list|(
specifier|const
name|char
modifier|*
name|prompt
parameter_list|,
name|int
name|echo
parameter_list|)
function_decl|;
end_function_decl
begin_endif
endif|#
directive|endif
end_endif
begin_comment
comment|/* COMPAT_TERMINAL_H */
end_comment
end_unit
