begin_unit
begin_comment
comment|/*  * SHA-1 implementation optimized for ARM  *  * Copyright:	(C) 2005 by Nicolas Pitre<nico@cam.org>  * Created:	September 17, 2005  */
end_comment
begin_include
include|#
directive|include
file|<stdint.h>
end_include
begin_typedef
DECL|struct|sha_context
typedef|typedef
struct|struct
name|sha_context
block|{
DECL|member|len
name|uint64_t
name|len
decl_stmt|;
DECL|member|hash
name|uint32_t
name|hash
index|[
literal|5
index|]
decl_stmt|;
DECL|member|buffer
name|unsigned
name|char
name|buffer
index|[
literal|64
index|]
decl_stmt|;
block|}
DECL|typedef|SHA_CTX
name|SHA_CTX
typedef|;
end_typedef
begin_function_decl
name|void
name|SHA1_Init
parameter_list|(
name|SHA_CTX
modifier|*
name|c
parameter_list|)
function_decl|;
end_function_decl
begin_function_decl
name|void
name|SHA1_Update
parameter_list|(
name|SHA_CTX
modifier|*
name|c
parameter_list|,
specifier|const
name|void
modifier|*
name|p
parameter_list|,
name|unsigned
name|long
name|n
parameter_list|)
function_decl|;
end_function_decl
begin_function_decl
name|void
name|SHA1_Final
parameter_list|(
name|unsigned
name|char
modifier|*
name|hash
parameter_list|,
name|SHA_CTX
modifier|*
name|c
parameter_list|)
function_decl|;
end_function_decl
end_unit
